name: Deploy Backend to Azure

on:
  push:
    branches:
      - main  # Trigger workflow when pushing to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run tests
      run: |
        pytest || echo "No tests found, continuing..."

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Azure Functions
      uses: azure/functions-action@v1
      with:
        app-name: func-resume-1760986821
        package: ./backend/api